sentences = [
    "Quick brown fox jumps over the lazy dog",
    "The five boxing wizards jump quickly",
    "Pack my box with five dozen liquor bottles",
    "She sells seashells by the seashore",
    "Early birds catch worms",
    "Practice makes perfect",
    "The cat sat on the mat",
    "Repetition is the mother of skill",
    "The quick, brown fox jumps over the lazy dog",
    "Proper planning prevents poor performance",
    "The early bird gets the worm",
    "It is raining cats and dogs outside",
    "Let's go for a walk in the park",
    "I love to eat pizza and ice cream",
    "She is a talented musician and dancer",
    "The children are playing in the garden",
    "The sixth sick sheik's sixth sheep's sick",
    "How can a clam cram in a clean cream can?",
    "Are you aware of the bare bear's dare?",
    "The boy bounced the ball",
    "The quick brown fox jumped over the lazy dog",
    "Hello there, said the friendly robot",
    "Wow! That's an amazing story",
    "She asked, What time is it?",
    "I can't believe it's already 9:00 PM",
    "There are 12 months in a year",
    "She has 3 cats and 2 dogs",
    "The price is $99.99",
    "My phone number is 555-1234"]